add logging
AlmaLinux/almalinux-deploy pull request #49
Opened 2021-04-20 14:36 UTC by titan-dn

- print UEK kernels list for migrating from Oracle
- print stdout to /var/log/almalinux-deploy.log

2021-04-21 08:54 UTC, soksanichenko requested changes

2021-04-21 08:54 UTC, soksanichenko commented on almalinux-deploy.sh
> +output=$(rpm -qa | grep kernel-uek) || :
var `output` should be local

2021-04-21 08:54 UTC, soksanichenko commented on almalinux-deploy.sh
> +check_custom_kernel() {
use indent for body of function

2021-04-21 08:54 UTC, soksanichenko commented on almalinux-deploy.sh
> +if [ -n "${output}" ]; then
Why do we not use double brackets?

2021-04-21 08:54 UTC, soksanichenko commented on almalinux-deploy.sh
> +    echo $output | sed 's# #\n#'
better `echo "${output}"` than this

2021-04-21 08:54 UTC, soksanichenko commented on almalinux-deploy.sh
> +    echo -e "[31;1mYou've had kernels that now can't be booting[0m:"
I think it's not informative message for user. I suggest to add info about what should do a client in this case and why its server can't be booting

2021-04-21 09:38 UTC, titan-dn commented on almalinux-deploy.sh
> +if [ -n "${output}" ]; then
it doesn't matter in this case

2021-04-21 13:37 UTC, soksanichenko approved these changes

2021-04-21 13:43 UTC, andrewlukoshko commented on almalinux-deploy.sh
> +        echo -ne "\n!! [31;1mYou've had kernels that can't be booted in
There are kernels left from previous operating system:

2021-04-22 13:47 UTC, soksanichenko approved these changes
Looks ok

2021-04-22 13:48 UTC, andrewlukoshko commented on almalinux-deploy.sh
> +            echo -ne "\n!! [31;1mYou've had kernels that can't be booted in
There are kernels left from previous operating system that won't boot in Secure Boot mode anymore:

2021-05-17 11:31 UTC, merged